sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t icarus2io/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true icarus2io/docker-react npm run test
